/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_programkasir;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ryan
 */
public class Main extends javax.swing.JFrame {
int disk,tohar,disk1,hrgbrg;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalharga = new javax.swing.JTextField();
        namakasir = new javax.swing.JTextField();
        namaitem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vrinda", 1, 36)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 124, 160, 40);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Vrinda", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(68, 68, 68))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(510, 40, 220, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 90);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.setLayout(null);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 10, 80, 23);

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(100, 10, 80, 23);

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(190, 10, 80, 23);

        jButton4.setText("PRINT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(280, 10, 80, 23);

        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(370, 10, 90, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 100, 550, 40);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setLayout(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 130, 100, 30);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel5.add(jPanel7);
        jPanel7.setBounds(20, 20, 110, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 210, 50);
        jPanel3.add(totalharga);
        totalharga.setBounds(10, 320, 190, 30);
        jPanel3.add(namakasir);
        namakasir.setBounds(10, 140, 190, 30);
        jPanel3.add(namaitem);
        namaitem.setBounds(10, 260, 190, 30);

        jLabel4.setText("Nama Item ( Makanan / Minuman ) :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 230, 190, 30);

        jLabel5.setText("Nama Kasir :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 110, 180, 30);

        jLabel6.setText("Tanggal Pembelian :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 170, 120, 30);

        jLabel7.setText("Total Harga");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 290, 80, 30);

        jLabel8.setText("Nomor Transaksi :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 50, 110, 30);
        jPanel3.add(kode);
        kode.setBounds(10, 80, 190, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 100, 210, 360);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "NamaKasir", "TanggalBeli", "NamaItem", "Harga", "Diskon", "Bayar"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 150, 550, 310);

        setBounds(0, 0, 804, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = dateFormat.format(tglbeli.getDate());
    hrgbrg = Integer.parseInt(totalharga.getText());
    if(hrgbrg >= 200000){
    disk = hrgbrg * 10 / 100;
    tohar = hrgbrg - disk;
    }else{
    disk = 0;
    tohar = hrgbrg - disk;
    }
    String SQL = "INSERT INTO tb_transaksi (nomor,NamaKasir,TanggalBeli,NamaItem,Harga,Diskon,Bayar) VALUES("+kode.getText()+",'"+namakasir.getText()+"','"+tanggal+"','"+namaitem.getText()+"',"+totalharga.getText()+","+disk+","+tohar+");";
    int status = KoneksiDB.execute(SQL);
    if (status == 1){
        JOptionPane.showMessageDialog(this, "Data berhasil dimasukkan", "Berhasil ,We did it", JOptionPane.INFORMATION_MESSAGE);
        selectData();
    }else{
        JOptionPane.showMessageDialog(this, "Data gagal dimasukkan", "Coba Lagi Ya! :*", JOptionPane.WARNING_MESSAGE);
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    selectData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    kode.setText("");
    namakasir.setText("");
    tglbeli.setDate(null);
    namaitem.setText("");
    totalharga.setText("");
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int baris = tb1.getSelectedRow();
    if (baris != -1){
        kode.setText(tb1.getValueAt(baris, 0).toString());
        namakasir.setText(tb1.getValueAt(baris, 1).toString());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        Date dateFormat = null;
        try{
            dateFormat = date.parse(tb1.getValueAt(baris, 2).toString());
        }catch (ParseException ex){
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        tglbeli.setDate(dateFormat);
        namaitem.setText(tb1.getValueAt(baris, 3).toString());
        totalharga.setText(tb1.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tb1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int baris = tb1.getSelectedRow();
        if (baris != -1){
            String nomor = tb1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE nomor='"+nomor+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Berhasil, We Did It", JOptionPane.INFORMATION_MESSAGE);
            selectData();
            }else{
                 JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Coba Lagi Ya :*", JOptionPane.WARNING_MESSAGE);
            }
        }else{
             JOptionPane.showMessageDialog(this, "Pilih Baris Data Dulu Ya -__-", "Error", JOptionPane.INFORMATION_MESSAGE);
             selectData();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    MessageFormat header = new MessageFormat("Data transaksi pembelian");
    MessageFormat footer = new MessageFormat("Page (0,number,integer)");
    try {
        tb1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
    }catch (java.awt.print.PrinterException e){
        System.err.format("Cannot print %s&n", e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField namaitem;
    private javax.swing.JTextField namakasir;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables

     private void selectData() {
        String kolom[] = {"nomor", "NamaKasir", "TanggalBeli", "NamaItem", "Harga", "Diskon", "Bayar"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom); 
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
              String nomor = rs.getString(1);
              String NamaKasir = rs.getString(2);
              String TanggalBeli = rs.getString(3);
              String NamaItem = rs.getString(4);
              String Harga = rs.getString(5);
              String Diskon = rs.getString(6);
              String Bayar = rs.getString(7);
              String data[] = {nomor, NamaKasir, TanggalBeli, NamaItem, Harga, Diskon, Bayar};
              dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        tb1.setModel(dtm);
    }
    
}
